#!/bin/bash
export WLR_NO_HARDWARE_CURSORS=1
export XDG_CURRENT_DESKTOP=dwl
export XDG_SESSION_TYPE=wayland
export MOZ_ENABLE_WAYLAND=1

eval "$(gnome-keyring-daemon --start)"
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK

export PATH="$HOME/.local/bin:$PATH"

WM_BIN=dwl
WM_ARGS=
