exec("qs")
exec("waybar")
exec("inhibit-idle-on-audio")
exec("swayidle -w timeout 300 'gaussian-lock' timeout 360 'systemctl suspend' before-sleep 'gaussian-lock'")
exec("mako")
exec("nm-applet")
exec("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
exec("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=dwl")
exec("nm-applet --indicator")
