general {
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false

    before_sleep_cmd = waterbear-lock
    inhibit_sleep = 3
    after_sleep_cmd = hyprctl dispatch dpms on
}

# after 8 mins you get brightness 
listener {
    timeout = 480
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# after 10 mins you get the lock
listener {
    timeout = 600
    on-timeout = waterbear-lock
}

# after 15 mins you get the screen off
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
}

# after 30 mins you get full sleep
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
