# Use 'lch' for perceptually accurate colors
color_space = "lch"
palette = "dark16"
check_contrast = true

[thresholds]
threshold = 22 # for constrast
min_lw = 2 # not too dark
max_lw = 15 # not too light

[templates]
firefox = { template = 'firefox', target = '~/.config/waterbear/mozilla/firefox/k7xxxbi1.default-release/chrome/wallust.css' }
foot = { template = 'foot', target = '~/.config/waterbear/foot/foot.ini' }
hypr = { template = 'hypr', target = '~/.cache/hypr/colors.lua' }
mako = { template = 'mako', target = '~/.config/waterbear/mako/config' }
qml = { template = 'qml', target = '~/.cache/qml/WallustTheme/Colors.qml' }
swaylock = { template = 'swaylock', target = '~/.cache/swaylock/colors.sh' }
starship = { template = 'starship.toml', target = '~/.starship.toml' }
wmenu = { template = 'wmenu', target = '~/.cache/wmenu/colors.sh' }
