# Use 'lch' for perceptually accurate colors
color_space = "lch"
palette = "dark"
check_contrast = true

[thresholds]
threshold = 22 # for constrast
min_lw = 2 # not too dark
max_lw = 15 # not too light

[templates]
foot = { template = 'foot', target = '~/.config/waterbear/foot/foot.ini' }
mako = { template = 'mako', target = '~/.config/waterbear/mako/config' }
wmenu = { template = 'wmenu', target = '~/.cache/wmenu/colors.sh' }
qml = { template = 'qml', target = '~/.cache/qml/WallustTheme/Colors.qml' }
swaylock = { template = 'swaylock', target = '~/.cache/swaylock/colors.sh' }
