#!/bin/bash

# Wayland
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland

# Browser/electron wayland support
export MOZ_ENABLE_WAYLAND=1
export NIXOS_OZONE_WL=1
export ELECTRON_OZONE_PLATFORM_HINT=auto

# Qt
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# GTK
export GDK_BACKEND=wayland,x11

# SDL
export SDL_VIDEODRIVER=wayland

# Java
export _JAVA_AWT_WM_NONREPARENTING=1

# xdg portals
export XDG_PORTAL_DIR="/usr/share/xdg-desktop-portal/portals"

# keyring
eval "$(gnome-keyring-daemon --start)"
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK

# user bin
export PATH="$HOME/.local/bin:$PATH"

# session binary
WM_BIN=Hyprland
WM_ARGS=""
